apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook-permissions
  namespace: argo-events
spec:
  github:
    lanbingcloud-repo:
      organizations:
        - "lanbingcloud"
      webhook:
        endpoint: /lanbingcloud-repo
        port: "12000"
        method: POST
        url: http://webhook.pipeline1.119-8-58-20.nip.io:30080
      events:
        - "repository"
      apiToken:
        key: token
        name: github-access
      wehookSecret:
        key: secret
        name: github-access
      insecure: true
      active: true
      contentType: json
    lanbingcloud-team:
      organizations:
        - "lanbingcloud"
      webhook:
        endpoint: /lanbingcloud-team
        port: "12000"
        method: POST
        url: http://webhook.pipeline1.119-8-58-20.nip.io:30080
      events:
        - "team"
      apiToken:
        key: token
        name: github-access
      wehookSecret:
        key: secret
        name: github-access
      insecure: true
      active: true
      contentType: json
