apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- eventbus.yaml
- secretstore.yaml
- external-github-access.yaml
- eventsource.yaml
- ingress-webhook-eventsource.yaml
- sensor-permissions-syncer.yaml
- rbac.yaml
namespace: argo-events
